### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by charlesroddie** [verybadcat/CSharpMath#23] opened 2018-12-12 23:29 UTC
We are getting large memory leaks when using CSharpMath.SkiaSharp on UWP. (@j-sauer do we get this on iOS too when moving back and forth between questions or graphs?) We don't have much info yet but will update as it comes in.

This may be related to a more general SkiaSharp bug but we need to isolate the problem seriously.

@sir-deenicus can you provide any info here as you debug this? @Happypig375 are you also seeing non-disposal of CSharpMath SkiaSharp objects?

**Comment by charlesroddie** [comment] 2018-12-14 15:02
@sir-deenicus do you have a repro?

**Comment by sir-deenicus** [comment] 2018-12-15 21:42
The error seems to occur somewhere in th path of invalidation of views backed by the OpenGL renderer. I'm not sure what's going on exactly but that path seems to be a big part of the issue.

Checking a mem-profiler, the call path
SkiaSharp.Views.UWP.SKSwapChainPanel::OnRenderFrame =>
SkiaSharp.Views.UWP.AngleSwapChainPanel::RenderFrame =>
SkiaSharp.Views.UWP.AngleSwapChainPanel::Invalidate
from
SkiaSharp.Views.UWP.dll
was most heavily indicated of the things that weren't just blackboxed into external 

I wrote a small self-contained [project](https://github.com/verybadcat/CSharpMath/files/2683083/skia-leak-min.zip) and made a few measurements recorded in this [spreadsheet.](https://github.com/verybadcat/CSharpMath/files/2683085/mem-leak.xlsx)

The protocol is meant to simulate or get an idea of memory use over time. On each click, 150 controls are generated and added to a stacklayout then cleared, 30 times. After clicking a button, I wait for that process to complete, press clear (which GCs), clicking twice. Set 1..4 represent this being done 4 times for each category. Each category is done by closing the program to start from scratch. 

You can see that GLView is most problematic. And that with CSharpMath, rendering uses so much memory I don't bother with more than 1 measurement.

![image](https://user-images.githubusercontent.com/1200050/50047590-882ace80-00b8-11e9-8f4f-5f1fdc05609d.png)

I'm not sure exactly the cause of this memory leak but know only that it's related to GLView.

**Comment by Happypig375** [comment] 2018-12-17 10:54
![image](https://user-images.githubusercontent.com/19922066/50082787-c5b06880-022c-11e9-8db0-d1c76ae0e26d.png)
It seems that `SkiaSharp.Views.UWP.SKSwapChainPanel` and `Container<Object, EventRegistrationTokenListWithCount>` is allocated more than needed.

**Comment by Happypig375** [comment] 2018-12-19 09:43
<details><summary>I have reduced the leak to this piece of long code:</summary>

    public class DrawInstructions : SKGLView
    {
        public class SkiaCanvas
        {
            public SkiaCanvas(SKCanvas canvas, SKStrokeCap strokeCap, bool? antiAliasLevel)
            {
                Canvas = canvas;
                StrokeCap = strokeCap;
                _paint = new SKPaint
                {
                    IsAntialias = antiAliasLevel != null,
                    SubpixelText = antiAliasLevel == true,
                    HintingLevel = SKPaintHinting.Full
                };
                CurrentStyle = default;
                CurrentColor = default;
                DefaultColor = default;
            }
            public SKCanvas Canvas { get; }
            public float Width => Canvas.LocalClipBounds.Width;
            public float Height => Canvas.LocalClipBounds.Height;
            public SKStrokeCap StrokeCap { get; set; }
            public SKColor DefaultColor { get; set; }
            public SKColor? CurrentColor { get; set; }
            public PaintStyle CurrentStyle { get; set; }

            private SKPaint _paint;
            private SKPaint StyledPaint(PaintStyle style, float? strokeWidth = null)
            {
                //In SkiaSharp, line will still be visible even if width is 0
                _paint.Color = strokeWidth == 0 ? SKColors.Transparent : (CurrentColor ?? DefaultColor);
                _paint.Style = (SKPaintStyle)style;
                _paint.StrokeWidth = strokeWidth ?? 0;
                _paint.StrokeCap = StrokeCap;
                return _paint;
            }
            internal SKPaint Paint => StyledPaint(CurrentStyle);
            private SKColor Color => CurrentColor ?? DefaultColor;

            //Canvas methods
            public void StrokeRect(float left, float top, float width, float height) => Canvas.DrawRect(SKRect.Create(left, top, width, height), StyledPaint(PaintStyle.Stroke));
            public void FillRect(float left, float top, float width, float height) => Canvas.DrawRect(SKRect.Create(left, top, width, height), StyledPaint(PaintStyle.Fill));
            public void DrawLine(float x1, float y1, float x2, float y2, float lineThickness) => Canvas.DrawLine(x1, y1, x2, y2, StyledPaint(PaintStyle.Stroke, lineThickness));
            public void Save() => Canvas.Save();
            public void Translate(float dx, float dy) => Canvas.Translate(dx, dy);
            public void Scale(float sx, float sy) => Canvas.Scale(sx, sy);
            public void Restore() => Canvas.Restore();
            public void FillText(string text, float x, float y, float pointSize) => Canvas.DrawText(text, x, y, new SKPaint { Color = Color, TextSize = pointSize, IsAntialias = true });

            public SkiaPath GetPath() => new SkiaPath(this);
        }
        public class SkiaPath
        {
            public SkiaPath(SkiaCanvas owner) => _owner = owner;

            private SkiaCanvas _owner;
            private SKPath _path = new SKPath();
            public void BeginRead() { }
            public void EndRead()
            {
                _owner.Canvas.DrawPath(_path, _owner.Paint);
                _path.Dispose();
                _path = null;
                _owner = null;
            }
            public void CloseContour() => _path.Close();
            public void Curve3(float x1, float y1, float x2, float y2) => _path.QuadTo(x1, y1, x2, y2);
            public void Curve4(float x1, float y1, float x2, float y2, float x3, float y3) => _path.CubicTo(x1, y1, x2, y2, x3, y3);
            public void LineTo(float x1, float y1) => _path.LineTo(x1, y1);
            public void MoveTo(float x0, float y0) { _path.Close(); _path.MoveTo(x0, y0); }
        }
        protected override void OnPaintSurface(SKPaintGLSurfaceEventArgs e)
        {
            var canvas = new SkiaCanvas(e.Surface.Canvas, SKStrokeCap.Butt, true);
            SkiaPath path;
            canvas.Save();
            canvas.Scale(1f, -1f);
            canvas.Scale(1f, 1f);
            canvas.DefaultColor = new SKColor(0, 0, 0, 255);
            canvas.CurrentColor = new SKColor(0, 0, 0, 0);
            canvas.CurrentStyle = PaintStyle.Fill;
            canvas.FillRect(0f, -31.51733f, 144.8791f, 31.51733f);
            canvas.CurrentColor = null;
            canvas.Save();
            canvas.Translate(0f, 0f);
            canvas.Translate(0f, 0f);
            canvas.Save();
            canvas.Translate(0f, 0f);
            canvas.Translate(0f, 0f);
            canvas.Save();
            canvas.Translate(0f, -22.112f);
            canvas.Translate(0f, 0f);
            canvas.Save();
            canvas.Translate(0f, 0.0133338f);
            canvas.Translate(0f, 0f);
            canvas.Save();
            canvas.CurrentColor = null;
            canvas.Translate(0f, 0f);
            path = canvas.GetPath();
            path.BeginRead();
            path.MoveTo(16.24f, 19.25333f);
            path.Curve4(16.24f, 20.53333f, 14.90667f, 21.46667f, 13.30667f, 21.46667f);
            path.Curve4(10.77333f, 21.46667f, 9.733333f, 18.88f, 9.28f, 16.85333f);
            path.Curve4(8.96f, 15.38667f, 8f, 7.866666f, 7.76f, 4.64f);
            path.LineTo(7.253333f, -2f);
            path.Curve4(6.906666f, -6.373333f, 5.946666f, -7.573333f, 4.426666f, -7.573333f);
            path.Curve4(4.08f, -7.573333f, 3.28f, -7.493333f, 2.72f, -7.013333f);
            path.Curve4(3.493333f, -6.906666f, 3.706666f, -6.293333f, 3.706666f, -5.92f);
            path.Curve4(3.706666f, -5.146667f, 3.12f, -4.8f, 2.613333f, -4.8f);
            path.Curve4(2.08f, -4.8f, 1.493333f, -5.146667f, 1.493333f, -5.946666f);
            path.Curve4(1.493333f, -7.226666f, 2.826667f, -8.16f, 4.426666f, -8.16f);
            path.Curve4(6.96f, -8.16f, 8.24f, -5.84f, 8.826666f, -3.44f);
            path.Curve4(9.173333f, -2.053333f, 10.13333f, 5.706666f, 10.34667f, 8.666666f);
            path.LineTo(10.85333f, 15.30667f);
            path.Curve4(11.22667f, 20.21333f, 12.13333f, 20.88f, 13.33333f, 20.88f);
            path.Curve4(13.6f, 20.88f, 14.42667f, 20.82667f, 15.01333f, 20.32f);
            path.Curve4(14.24f, 20.21333f, 14.02667f, 19.6f, 14.02667f, 19.22667f);
            path.Curve4(14.02667f, 18.45333f, 14.61333f, 18.10667f, 15.12f, 18.10667f);
            path.Curve4(15.65333f, 18.10667f, 16.24f, 18.45333f, 16.24f, 19.25333f);
            path.CloseContour();
            path.EndRead();
            canvas.Restore();
            canvas.Restore();
            canvas.Save();
            canvas.Translate(21.06667f, 0f);
            canvas.Save();
            canvas.Save();
            canvas.Translate(0f, 0f);
            canvas.CurrentColor = null;
            path = canvas.GetPath();
            path.BeginRead();
            path.MoveTo(11.97333f, 4.64f);
            path.LineTo(11.30667f, 4.64f);
            path.Curve4(11.17333f, 3.84f, 10.98667f, 2.666667f, 10.72f, 2.266667f);
            path.Curve4(10.53333f, 2.053333f, 8.773333f, 2.053333f, 8.186666f, 2.053333f);
            path.LineTo(3.386667f, 2.053333f);
            path.LineTo(6.213333f, 4.8f);
            path.Curve4(10.37333f, 8.48f, 11.97333f, 9.919999f, 11.97333f, 12.58667f);
            path.Curve4(11.97333f, 15.62667f, 9.573333f, 17.76f, 6.32f, 17.76f);
            path.Curve4(3.306667f, 17.76f, 1.333333f, 15.30667f, 1.333333f, 12.93333f);
            path.Curve4(1.333333f, 11.44f, 2.666667f, 11.44f, 2.746666f, 11.44f);
            path.Curve4(3.2f, 11.44f, 4.133333f, 11.76f, 4.133333f, 12.85333f);
            path.Curve4(4.133333f, 13.54667f, 3.653333f, 14.24f, 2.72f, 14.24f);
            path.Curve4(2.506667f, 14.24f, 2.453333f, 14.24f, 2.373333f, 14.21333f);
            path.Curve4(2.986666f, 15.94667f, 4.426666f, 16.93333f, 5.973333f, 16.93333f);
            path.Curve4(8.4f, 16.93333f, 9.546666f, 14.77333f, 9.546666f, 12.58667f);
            path.Curve4(9.546666f, 10.45333f, 8.213333f, 8.346666f, 6.746666f, 6.693333f);
            path.LineTo(1.626667f, 0.9866666f);
            path.Curve4(1.333333f, 0.6933333f, 1.333333f, 0.64f, 1.333333f, 0f);
            path.LineTo(11.22667f, 0f);
            path.CloseContour();
            path.EndRead();
            canvas.Translate(13.33333f, 0f);
            path = canvas.GetPath();
            path.BeginRead();
            path.MoveTo(14.05333f, 10.02667f);
            path.Curve4(14.05333f, 11.41333f, 12.48f, 11.78667f, 11.57333f, 11.78667f);
            path.Curve4(10.02667f, 11.78667f, 9.093333f, 10.37333f, 8.773333f, 9.759999f);
            path.Curve4(8.106667f, 11.52f, 6.666667f, 11.78667f, 5.893333f, 11.78667f);
            path.Curve4(3.12f, 11.78667f, 1.6f, 8.346666f, 1.6f, 7.68f);
            path.Curve4(1.6f, 7.413333f, 1.92f, 7.413333f, 1.92f, 7.413333f);
            path.Curve4(2.133333f, 7.413333f, 2.213333f, 7.466666f, 2.266667f, 7.706666f);
            path.Curve4(3.173333f, 10.53333f, 4.933333f, 11.2f, 5.84f, 11.2f);
            path.Curve4(6.346666f, 11.2f, 7.28f, 10.96f, 7.28f, 9.413333f);
            path.Curve4(7.28f, 8.586666f, 6.826666f, 6.8f, 5.84f, 3.066667f);
            path.Curve4(5.413333f, 1.413333f, 4.48f, 0.2933333f, 3.306667f, 0.2933333f);
            path.Curve4(3.146667f, 0.2933333f, 2.533333f, 0.2933333f, 1.973333f, 0.64f);
            path.Curve4(2.64f, 0.7733333f, 3.226666f, 1.333333f, 3.226666f, 2.08f);
            path.Curve4(3.226666f, 2.8f, 2.64f, 3.013333f, 2.24f, 3.013333f);
            path.Curve4(1.44f, 3.013333f, 0.7733333f, 2.32f, 0.7733333f, 1.466667f);
            path.Curve4(0.7733333f, 0.24f, 2.106667f, -0.2933333f, 3.28f, -0.2933333f);
            path.Curve4(5.04f, -0.2933333f, 6f, 1.573333f, 6.08f, 1.733333f);
            path.Curve4(6.4f, 0.7466666f, 7.36f, -0.2933333f, 8.96f, -0.2933333f);
            path.Curve4(11.70667f, -0.2933333f, 13.22667f, 3.146667f, 13.22667f, 3.813333f);
            path.Curve4(13.22667f, 4.08f, 12.98667f, 4.08f, 12.90667f, 4.08f);
            path.Curve4(12.66667f, 4.08f, 12.61333f, 3.973333f, 12.56f, 3.786666f);
            path.Curve4(11.68f, 0.9333333f, 9.866666f, 0.2933333f, 9.013333f, 0.2933333f);
            path.Curve4(7.973333f, 0.2933333f, 7.546666f, 1.146667f, 7.546666f, 2.053333f);
            path.Curve4(7.546666f, 2.64f, 7.706666f, 3.226666f, 8f, 4.4f);
            path.LineTo(8.906666f, 8.053333f);
            path.Curve4(9.066667f, 8.746666f, 9.679999f, 11.2f, 11.54667f, 11.2f);
            path.Curve4(11.68f, 11.2f, 12.32f, 11.2f, 12.88f, 10.85333f);
            path.Curve4(12.13333f, 10.72f, 11.6f, 10.05333f, 11.6f, 9.413333f);
            path.Curve4(11.6f, 8.986667f, 11.89333f, 8.48f, 12.61333f, 8.48f);
            path.Curve4(13.2f, 8.48f, 14.05333f, 8.96f, 14.05333f, 10.02667f);
            path.CloseContour();
            path.EndRead();
            canvas.Translate(15.25333f, 0f);
            canvas.Restore();
            canvas.Restore();
            canvas.Restore();
            canvas.Save();
            canvas.Translate(49.65333f, 9.679999f);
            canvas.Translate(0f, 0f);
            canvas.Save();
            canvas.Translate(0f, 0f);
            canvas.Save();
            canvas.Save();
            canvas.Translate(0f, 0f);
            canvas.CurrentColor = null;
            path = canvas.GetPath();
            path.BeginRead();
            path.MoveTo(8.381333f, 3.248f);
            path.LineTo(7.914666f, 3.248f);
            path.Curve4(7.821333f, 2.688f, 7.690666f, 1.866667f, 7.504f, 1.586667f);
            path.Curve4(7.373333f, 1.437333f, 6.141333f, 1.437333f, 5.730667f, 1.437333f);
            path.LineTo(2.370667f, 1.437333f);
            path.LineTo(4.349333f, 3.36f);
            path.Curve4(7.261333f, 5.936f, 8.381333f, 6.944f, 8.381333f, 8.810666f);
            path.Curve4(8.381333f, 10.93867f, 6.701333f, 12.432f, 4.424f, 12.432f);
            path.Curve4(2.314667f, 12.432f, 0.9333333f, 10.71467f, 0.9333333f, 9.053333f);
            path.Curve4(0.9333333f, 8.007999f, 1.866667f, 8.007999f, 1.922667f, 8.007999f);
            path.Curve4(2.24f, 8.007999f, 2.893333f, 8.231999f, 2.893333f, 8.997333f);
            path.Curve4(2.893333f, 9.482666f, 2.557333f, 9.967999f, 1.904f, 9.967999f);
            path.Curve4(1.754667f, 9.967999f, 1.717333f, 9.967999f, 1.661333f, 9.949333f);
            path.Curve4(2.090667f, 11.16267f, 3.098667f, 11.85333f, 4.181333f, 11.85333f);
            path.Curve4(5.88f, 11.85333f, 6.682666f, 10.34133f, 6.682666f, 8.810666f);
            path.Curve4(6.682666f, 7.317333f, 5.749333f, 5.842667f, 4.722666f, 4.685333f);
            path.LineTo(1.138667f, 0.6906666f);
            path.Curve4(0.9333333f, 0.4853333f, 0.9333333f, 0.448f, 0.9333333f, 0f);
            path.LineTo(7.858666f, 0f);
            path.CloseContour();
            path.EndRead();
            canvas.Translate(9.333333f, 0f);
            canvas.Restore();
            canvas.Restore();
            canvas.Restore();
            canvas.Restore();
            canvas.Save();
            canvas.Translate(64.92444f, 0f);
            canvas.Save();
            canvas.Save();
            canvas.Translate(0f, 0f);
            canvas.CurrentColor = null;
            path = canvas.GetPath();
            path.BeginRead();
            path.MoveTo(19.25333f, 6.666667f);
            path.Curve4(19.25333f, 6.96f, 19.01333f, 7.2f, 18.72f, 7.2f);
            path.LineTo(10.90667f, 7.2f);
            path.LineTo(10.90667f, 15.01333f);
            path.Curve4(10.90667f, 15.30667f, 10.66667f, 15.54667f, 10.37333f, 15.54667f);
            path.Curve4(10.08f, 15.54667f, 9.839999f, 15.30667f, 9.839999f, 15.01333f);
            path.LineTo(9.839999f, 7.2f);
            path.LineTo(2.026667f, 7.2f);
            path.Curve4(1.733333f, 7.2f, 1.493333f, 6.96f, 1.493333f, 6.666667f);
            path.Curve4(1.493333f, 6.373333f, 1.733333f, 6.133333f, 2.026667f, 6.133333f);
            path.LineTo(9.839999f, 6.133333f);
            path.LineTo(9.839999f, -1.68f);
            path.Curve4(9.839999f, -1.973333f, 10.08f, -2.213333f, 10.37333f, -2.213333f);
            path.Curve4(10.66667f, -2.213333f, 10.90667f, -1.973333f, 10.90667f, -1.68f);
            path.LineTo(10.90667f, 6.133333f);
            path.LineTo(18.72f, 6.133333f);
            path.Curve4(19.01333f, 6.133333f, 19.25333f, 6.373333f, 19.25333f, 6.666667f);
            path.CloseContour();
            path.EndRead();
            canvas.Translate(25.19111f, 0f);
            path = canvas.GetPath();
            path.BeginRead();
            path.MoveTo(14.05333f, 10.02667f);
            path.Curve4(14.05333f, 11.41333f, 12.48f, 11.78667f, 11.57333f, 11.78667f);
            path.Curve4(10.02667f, 11.78667f, 9.093333f, 10.37333f, 8.773333f, 9.759999f);
            path.Curve4(8.106667f, 11.52f, 6.666667f, 11.78667f, 5.893333f, 11.78667f);
            path.Curve4(3.12f, 11.78667f, 1.6f, 8.346666f, 1.6f, 7.68f);
            path.Curve4(1.6f, 7.413333f, 1.92f, 7.413333f, 1.92f, 7.413333f);
            path.Curve4(2.133333f, 7.413333f, 2.213333f, 7.466666f, 2.266667f, 7.706666f);
            path.Curve4(3.173333f, 10.53333f, 4.933333f, 11.2f, 5.84f, 11.2f);
            path.Curve4(6.346666f, 11.2f, 7.28f, 10.96f, 7.28f, 9.413333f);
            path.Curve4(7.28f, 8.586666f, 6.826666f, 6.8f, 5.84f, 3.066667f);
            path.Curve4(5.413333f, 1.413333f, 4.48f, 0.2933333f, 3.306667f, 0.2933333f);
            path.Curve4(3.146667f, 0.2933333f, 2.533333f, 0.2933333f, 1.973333f, 0.64f);
            path.Curve4(2.64f, 0.7733333f, 3.226666f, 1.333333f, 3.226666f, 2.08f);
            path.Curve4(3.226666f, 2.8f, 2.64f, 3.013333f, 2.24f, 3.013333f);
            path.Curve4(1.44f, 3.013333f, 0.7733333f, 2.32f, 0.7733333f, 1.466667f);
            path.Curve4(0.7733333f, 0.24f, 2.106667f, -0.2933333f, 3.28f, -0.2933333f);
            path.Curve4(5.04f, -0.2933333f, 6f, 1.573333f, 6.08f, 1.733333f);
            path.Curve4(6.4f, 0.7466666f, 7.36f, -0.2933333f, 8.96f, -0.2933333f);
            path.Curve4(11.70667f, -0.2933333f, 13.22667f, 3.146667f, 13.22667f, 3.813333f);
            path.Curve4(13.22667f, 4.08f, 12.98667f, 4.08f, 12.90667f, 4.08f);
            path.Curve4(12.66667f, 4.08f, 12.61333f, 3.973333f, 12.56f, 3.786666f);
            path.Curve4(11.68f, 0.9333333f, 9.866666f, 0.2933333f, 9.013333f, 0.2933333f);
            path.Curve4(7.973333f, 0.2933333f, 7.546666f, 1.146667f, 7.546666f, 2.053333f);
            path.Curve4(7.546666f, 2.64f, 7.706666f, 3.226666f, 8f, 4.4f);
            path.LineTo(8.906666f, 8.053333f);
            path.Curve4(9.066667f, 8.746666f, 9.679999f, 11.2f, 11.54667f, 11.2f);
            path.Curve4(11.68f, 11.2f, 12.32f, 11.2f, 12.88f, 10.85333f);
            path.Curve4(12.13333f, 10.72f, 11.6f, 10.05333f, 11.6f, 9.413333f);
            path.Curve4(11.6f, 8.986667f, 11.89333f, 8.48f, 12.61333f, 8.48f);
            path.Curve4(13.2f, 8.48f, 14.05333f, 8.96f, 14.05333f, 10.02667f);
            path.CloseContour();
            path.EndRead();
            canvas.Translate(19.69778f, 0f);
            path = canvas.GetPath();
            path.BeginRead();
            path.MoveTo(19.25333f, 6.666667f);
            path.Curve4(19.25333f, 6.96f, 19.01333f, 7.2f, 18.72f, 7.2f);
            path.LineTo(2.026667f, 7.2f);
            path.Curve4(1.733333f, 7.2f, 1.493333f, 6.96f, 1.493333f, 6.666667f);
            path.Curve4(1.493333f, 6.373333f, 1.733333f, 6.133333f, 2.026667f, 6.133333f);
            path.LineTo(18.72f, 6.133333f);
            path.Curve4(19.01333f, 6.133333f, 19.25333f, 6.373333f, 19.25333f, 6.666667f);
            path.CloseContour();
            path.EndRead();
            canvas.Translate(20.74667f, 0f);
            canvas.Restore();
            canvas.Restore();
            canvas.Restore();
            canvas.Save();
            canvas.Translate(135.0044f, 10.50667f);
            canvas.Translate(0f, 0f);
            canvas.Save();
            canvas.Translate(0f, 0f);
            canvas.Save();
            canvas.Save();
            canvas.Translate(0f, 0f);
            canvas.CurrentColor = null;
            path = canvas.GetPath();
            path.BeginRead();
            path.MoveTo(9.296f, 2.669333f);
            path.Curve4(9.296f, 2.856f, 9.127999f, 2.856f, 9.072f, 2.856f);
            path.Curve4(8.885333f, 2.856f, 8.866667f, 2.781333f, 8.810666f, 2.52f);
            path.Curve4(8.493333f, 1.306667f, 8.157333f, 0.2053333f, 7.392f, 0.2053333f);
            path.Curve4(6.888f, 0.2053333f, 6.832f, 0.6906666f, 6.832f, 1.064f);
            path.Curve4(6.832f, 1.474667f, 6.869333f, 1.624f, 7.074667f, 2.445333f);
            path.LineTo(7.485333f, 4.125333f);
            path.LineTo(8.157333f, 6.738667f);
            path.Curve4(8.288f, 7.261333f, 8.288f, 7.298666f, 8.288f, 7.373333f);
            path.Curve4(8.288f, 7.690666f, 8.064f, 7.877333f, 7.746666f, 7.877333f);
            path.Curve4(7.298666f, 7.877333f, 7.018666f, 7.466666f, 6.962667f, 7.056f);
            path.Curve4(6.626667f, 7.746666f, 6.085333f, 8.250667f, 5.245333f, 8.250667f);
            path.Curve4(3.061333f, 8.250667f, 0.7466667f, 5.506667f, 0.7466667f, 2.781333f);
            path.Curve4(0.7466667f, 1.026667f, 1.773333f, -0.2053333f, 3.229333f, -0.2053333f);
            path.Curve4(3.602667f, -0.2053333f, 4.536f, -0.1306667f, 5.656f, 1.194667f);
            path.Curve4(5.805333f, 0.4106666f, 6.458666f, -0.2053333f, 7.354666f, -0.2053333f);
            path.Curve4(8.007999f, -0.2053333f, 8.437333f, 0.224f, 8.736f, 0.8213333f);
            path.Curve4(9.053333f, 1.493333f, 9.296f, 2.669333f, 9.296f, 2.669333f);
            path.MoveTo(6.738667f, 6.197333f);
            path.Curve4(6.738667f, 6.085333f, 6.701333f, 5.973333f, 6.682666f, 5.88f);
            path.LineTo(5.749333f, 2.221333f);
            path.Curve4(5.656f, 1.885333f, 5.656f, 1.848f, 5.376f, 1.530667f);
            path.Curve4(4.554667f, 0.504f, 3.789333f, 0.2053333f, 3.266667f, 0.2053333f);
            path.Curve4(2.333333f, 0.2053333f, 2.072f, 1.232f, 2.072f, 1.96f);
            path.Curve4(2.072f, 2.893333f, 2.669333f, 5.189333f, 3.098667f, 6.048f);
            path.Curve4(3.677333f, 7.149333f, 4.517333f, 7.84f, 5.264f, 7.84f);
            path.Curve4(6.477333f, 7.84f, 6.738667f, 6.309333f, 6.738667f, 6.197333f);
            path.CloseContour();
            path.EndRead();
            canvas.Translate(9.874666f, 0f);
            canvas.Restore();
            canvas.Restore();
            canvas.Restore();
            canvas.Restore();
            canvas.Save();
            canvas.Translate(135.9378f, -9.2f);
            canvas.Translate(0f, 0f);
            canvas.Save();
            canvas.Translate(0f, 0f);
            canvas.Save();
            canvas.Save();
            canvas.Translate(0f, 0f);
            canvas.CurrentColor = null;
            path = canvas.GetPath();
            path.BeginRead();
            path.MoveTo(7.746666f, 5.264f);
            path.Curve4(7.746666f, 6.962667f, 6.757333f, 8.250667f, 5.264f, 8.250667f);
            path.Curve4(4.405333f, 8.250667f, 3.64f, 7.709333f, 3.08f, 7.130666f);
            path.LineTo(4.461333f, 12.74933f);
            path.Curve4(4.461333f, 12.74933f, 4.461333f, 12.95467f, 4.218667f, 12.95467f);
            path.Curve4(3.789333f, 12.95467f, 2.426666f, 12.80533f, 1.941333f, 12.768f);
            path.Curve4(1.792f, 12.74933f, 1.586667f, 12.73067f, 1.586667f, 12.39467f);
            path.Curve4(1.586667f, 12.17067f, 1.754667f, 12.17067f, 2.034667f, 12.17067f);
            path.Curve4(2.930666f, 12.17067f, 2.968f, 12.04f, 2.968f, 11.85333f);
            path.Curve4(2.968f, 11.72267f, 2.8f, 11.088f, 2.706666f, 10.696f);
            path.LineTo(1.176f, 4.610666f);
            path.Curve4(0.952f, 3.677333f, 0.8773333f, 3.378667f, 0.8773333f, 2.725333f);
            path.Curve4(0.8773333f, 0.952f, 1.866667f, -0.2053333f, 3.248f, -0.2053333f);
            path.Curve4(5.450666f, -0.2053333f, 7.746666f, 2.576f, 7.746666f, 5.264f);
            path.MoveTo(6.402667f, 6.085333f);
            path.Curve4(6.402667f, 4.984f, 5.786666f, 2.837333f, 5.450666f, 2.128f);
            path.Curve4(4.834667f, 0.8773333f, 3.976f, 0.2053333f, 3.248f, 0.2053333f);
            path.Curve4(2.613333f, 0.2053333f, 1.997333f, 0.7093333f, 1.997333f, 2.090667f);
            path.Curve4(1.997333f, 2.445333f, 1.997333f, 2.8f, 2.296f, 3.976f);
            path.LineTo(2.706666f, 5.693333f);
            path.Curve4(2.818666f, 6.104f, 2.818666f, 6.141333f, 2.986667f, 6.346666f);
            path.Curve4(3.901333f, 7.56f, 4.741333f, 7.84f, 5.226666f, 7.84f);
            path.Curve4(5.898666f, 7.84f, 6.402667f, 7.28f, 6.402667f, 6.085333f);
            path.CloseContour();
            path.EndRead();
            canvas.Translate(8.007999f, 0f);
            canvas.Restore();
            canvas.Restore();
            canvas.Restore();
            canvas.Restore();
            canvas.Save();
            canvas.CurrentColor = null;
            canvas.DrawLine(135.0044f, 6.666667f, 144.8791f, 6.666667f, 1.066667f);
            canvas.Restore();
            canvas.Restore();
            canvas.Restore();
            canvas.Save();
            canvas.Translate(0f, 0f);
            canvas.Translate(0f, 0f);
            canvas.Restore();
            canvas.Restore();
            canvas.Restore();
        }
    }
</details>

**Comment by Happypig375** [comment] 2018-12-19 09:43
Possible root cause: Save/Restore

**Comment by Happypig375** [comment] 2018-12-19 10:52
With anti alias:
![image](https://user-images.githubusercontent.com/19922066/50215778-faecc000-03be-11e9-8a9f-aba42cdba01e.png)
No anti-alias:
![image](https://user-images.githubusercontent.com/19922066/50215855-266faa80-03bf-11e9-8c4f-3ba6b23eec2b.png)

**Comment by Happypig375** [comment] 2018-12-19 11:50
So yeah, this isn't CSharpMath's fault.

**Comment by Happypig375** [comment] 2018-12-19 11:50
Awaiting https://github.com/mono/SkiaSharp/issues/705 to be fixed

**Comment by mattleibow** [comment] 2018-12-24 04:46
Just an update on this issue: https://github.com/mono/SkiaSharp/issues/705#issuecomment-449685449
> What was happening was the view was initializing ANGLE, and then releasing all the references and things - except for the final context. This left all sorts of references on the native side still hooked up inside the ANGLE library. As a result, even though the managed GC was all free, ANGLE was never told that it should let go of the views.

**Comment by Happypig375** [comment] 2018-12-26 08:30
Awaiting next SkiaSharp.Views.Forms prerelease

**Comment by mattleibow** [comment] 2019-01-02 15:11
I am  not sure if the new graph is a good one or not? It looks better - 500MB vs 2GB

**Closed** 2019-10-13 16:09 UTC
Labels: Resolution/Fixed, Type/Bug
