### ISSUE TITLE
TextView height doesn't work 

### ISSUE THREAD

**Issue by BenjaNapo** [verybadcat/CSharpMath#138] opened 2020-06-22 16:10 UTC
### Describe the bug
TextView height is not set properly based on text length, indeed it change drastically just adding a single character

### To Reproduce
I created two ListView with just one char of difference in this way:
```
                <ListView
                    Margin="0,10,0,0"
                    HasUnevenRows="true"
                    ItemTapped="ListView_ItemTapped"
                    ItemsSource="{Binding DomandaAttuale.Risposte}"
                    SelectionMode="None"
                    VerticalOptions="Center">
                    <ListView.ItemTemplate>
                        <DataTemplate>
                            <ViewCell>
                                <Grid VerticalOptions="CenterAndExpand">
                                    <Grid.ColumnDefinitions>
                                        <ColumnDefinition Width="1*" />
                                        <ColumnDefinition Width="9*" />
                                    </Grid.ColumnDefinitions>
                                    <ia:Checkbox
                                        FillColor="{DynamicResource PrimaryColor}"
                                        IsChecked="{Binding Selezionata}"
                                        IsCheckedChanged="Checkbox_IsCheckedChanged"
                                        OutlineColor="{DynamicResource PrimaryColor}"
                                        Shape="Circle" />
                                    <math:TextView
                                        Grid.Column="1"
                                        FontSize="35"
                                        LaTeX="L'insieme dei nu"
                                        TextAlignment="Left"
                                        VerticalOptions="Center" />
                                </Grid>
                            </ViewCell>
                        </DataTemplate>
                    </ListView.ItemTemplate>
                </ListView>
```

### Expected behavior
This is the result with the text "L'insieme dei nu":
![Screenshot_1592831636 (2)](https://user-images.githubusercontent.com/25958425/85309687-3f28b700-b4b3-11ea-8736-3970fc54171d.png)
 
And this is the result with the text "L'insieme dei num":
![Screenshot_1592831650 (2)](https://user-images.githubusercontent.com/25958425/85309694-4223a780-b4b3-11ea-9209-83d392e4144e.png)

**Comment by Happypig375** [comment] 2020-06-22 16:14
My instinct tells me that this is related to #136.

**Comment by BenjaNapo** [comment] 2020-06-22 16:20
I saw that issue too but I didn't know if they were related, but if you say so I'll follow that issue👌🏻 Hope it will work for mine too when fixed :P

**Comment by Happypig375** [comment] 2020-06-23 05:54
Not reproducing on latest `master`
 with
```xaml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:d="http://xamarin.com/schemas/2014/forms/design"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             xmlns:local="clr-namespace:CSharpMath.Forms;assembly=CSharpMath.Forms"
             mc:Ignorable="d"
             x:Class="CSharpMath.Forms.Example.Test">
    <ScrollView>
        <StackLayout>
            <local:TextView BackgroundColor="LightSalmon" HighlightColor="LightYellow" LaTeX="L'insieme dei nu"/>
            <local:TextView BackgroundColor="LightGreen" HighlightColor="LightBlue" LaTeX="L'insieme dei nu"/>
            <local:TextView BackgroundColor="LightSalmon" HighlightColor="LightYellow" LaTeX="L'insieme dei num"/>
            <local:TextView BackgroundColor="LightGreen" HighlightColor="LightBlue" LaTeX="L'insieme dei num"/>
            <ListView
                    Margin="0,10,0,0"
                    HasUnevenRows="true"
                    SelectionMode="None"
                    VerticalOptions="Center">
                <ListView.ItemsSource>
                    <x:Array Type="{x:Type x:Int32}">
                        <x:Int32>1</x:Int32>
                        <x:Int32>2</x:Int32>
                        <x:Int32>3</x:Int32>
                    </x:Array>
                </ListView.ItemsSource>
                <ListView.ItemTemplate>
                    <DataTemplate>
                        <ViewCell>
                            <Grid VerticalOptions="CenterAndExpand">
                                <Grid.ColumnDefinitions>
                                    <ColumnDefinition Width="1*" />
                                    <ColumnDefinition Width="9*" />
                                </Grid.ColumnDefinitions>
                                <CheckBox />
                                <local:TextView
                                        Grid.Column="1"
                                        FontSize="35"
                                        LaTeX="L'insieme dei num"
                                        TextAlignment="Left"
                                        VerticalOptions="Center" />
                            </Grid>
                        </ViewCell>
                    </DataTemplate>
                </ListView.ItemTemplate>
            </ListView>
        </StackLayout>
    </ScrollView>
</ContentPage>
```

![image](https://user-images.githubusercontent.com/19922066/85366014-1529d000-b559-11ea-9cbf-bb390e17aedd.png)

**Comment by BenjaNapo** [comment] 2020-06-24 10:00
I've downloaded the latest Nightly Package but it still the same:
![Screenshot_1592992538](https://user-images.githubusercontent.com/25958425/85534853-f89d9e80-b611-11ea-9ce4-b07fbe7d26f3.png)

Any idea? I don't think it's my """fault""" because it shows well writing "L'insieme dei nu"

**Comment by Happypig375** [comment] 2020-06-25 09:52
I cannot confirm this bug because I have not seen it happen yet and it is not debuggable. Try uploading a zipped file of a solution that exhibits this problem.

**Comment by Happypig375** [comment] 2020-07-19 05:10
This is probably fixed with #136 and #137. Can you confirm?

**Comment by MartinZikmund** [comment] 2020-07-19 08:38
Will check!

**Comment by BenjaNapo** [comment] 2020-07-23 11:15
Height issue resolved! Nice work 😁

**Closed** 2020-10-16 15:55 UTC
Labels: Resolution/Fixed, Status/5. Awaiting next release, Type/Bug
