### ISSUE TITLE
`sin^2` fails when getting LaTeX

### ISSUE THREAD

**Issue by charlesroddie** [verybadcat/CSharpMath#85] opened 2019-11-07 20:22 UTC
Steps to reproduce:
Enter `\sin^` in the Try part of the Forms example project, or attempt to enter `sin^2` in the Editor part.
Result:
```
Exception thrown: 'System.ArgumentNullException' in CSharpMath.dll
An exception of type 'System.ArgumentNullException' occurred in CSharpMath.dll but was not handled in user code
LaTeX Symbol name must not be null.
```
The atom gets constructed correctly, but getting latex fails.

Variables to powers and numbers to powers work, but functions to powers do not.

**Comment by charlesroddie** [comment] 2019-11-07 20:30
`{Large Operator sin}` is cast to `op:LargeOperator` and `MathAtoms.LatexSymbolNameForAtom(op)` returns `null`.

**Comment by FoggyFinder** [comment] 2019-11-07 20:34
Sounds like duplicate of #67

**Closed** 2019-11-07 20:47 UTC
Labels: Resolution/Duplicate, Type/Bug
